# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "v1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[override]]
  version = "0.0.0"
  name = "github.com/katzenpost/client"

[[override]]
  version = "0.0.6"
  name = "github.com/katzenpost/core"

[[override]]
  version = "0.0.4"
  name = "github.com/katzenpost/minclient"

# pin deps

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"